language: python
python:
  - 3.9

services:
  - docker

before_install:
  - python --version
  - wget -q0- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERUSER" --password-stdin
  - echo "$HEROKUPASSWORD" | docker login -u "$HEROKUUSER" --password-stdin registry.heroku.com

install:
  - pip install -U pip
  - pip install -U pytest

script: 
  - pytest # run tests
  - docker build -t bruno9817/ci_challenge .
  - docker tag bruno9817/ci_challenge registry.heroku.com/$HEROKUAPPNAME/web

after_success:

deploy:
  provider: script
  script:
    docker push bruno9817/ci_challenge;
    docker push registry.heroku.com/$HEROKUAPPNAME/web;
    heroku container:release web -a $HEROKUAPPNAME
  on:
    branch: main

notifications:
 email:
  on_success: always
  on_failure: always
