language: python
python:
  - 3.9

servuces:
  - docker

before_install:
  - python --version
  - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERUSER" --password-stdin

install:
  - pip install -U pip
  - pip install -U pytest

script: 
  - pytest # run tests
  - docker build -t bruno9817/ci_challenge .

after_success:

deploy:
  provider: script
  script:
    docker push ci_challenge;
  on:
    branch: main

notifications:
 email:
  on_success: always
  on_failure: always
