language: python
python:
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
script: pytest # run tests
after_success:
notifications:
 email:
  on_success: always
  on_failure: always
